{application,concurix_runtime,
             [{description,"Concurix VM Runtime enhancements"},
              {vsn,"0.1"},
              {src_dirs,["./"]},
              {registered,[]},
              {applications,[compiler,kernel,stdlib]},
              {env,[]},
              {modules,[concurix_compile,concurix_file,concurix_memo,
                        concurix_run,concurix_runtime,concurix_spawn,
                        concurix_transform]}]}.
